create database customer_analysis;
use customer_analysis;

-- 1.Total revenue generated by gender wise.
select gender,sum(purchase_amount)
from customer
group by gender;

-- 2.Which customers used a discount bill still spent more than the average purchase amount?  
select customer_id,purchase_amount 
from customer
where discount_applied="Yes" and purchase_amount>=
(select avg(purchase_amount) from customer);

-- 3.Top 5 products with highest average review ratings.
select item_purchased,round(avg(review_rating),2) as average_review_ratings
from customer
group by item_purchased
order by average_review_ratings desc
limit 5;

-- 4.Compare the average purchase amounts of different shipping type.
 select shipping_type,round(avg(purchase_amount),2) as average_purchase_amount
 from customer
 group by shipping_type
 order by average_purchase_amount desc;

-- 5.Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
round(avg(purchase_amount),2) as average_purchase_amount,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue desc;


-- 6.Top 3 selling item within each category.
with cte as(select category,item_purchased,
row_number() over(partition by category order by count(customer_id) desc) as rnk
from customer
group by category,item_purchased)
select * from cte where rnk<=3;

-- 7.Show number of customers who are New(one purchase), Returning(2-15 purchase) and Loyal(More than 15 purchase).
with cte as (select customer_id,previous_purchases,
case
when previous_purchases=1 then "New"
when previous_purchases between 2 and 15 then "Returning"
else "Loyal"
end as customer_category
from customer)
select customer_category,count(*)
from cte group by customer_category; 

-- 8.Top 5 coloured product which are liked most bu customers.  
select colour,count(*)
from customer
group by colour
order by count(*) desc
limit 5;

-- 9.Season wise top 5 selling items.
with cte as(select season,item_purchased,sum(purchase_amount),
row_number() over(partition by season order by sum(purchase_amount) desc) as rnk
from customer
group by item_purchased,season)
select * from cte where rnk<=5;

-- 10.How does review rating relate to purchase frequency?
with cte as(select customer_id,review_rating,
case
when review_rating between 4 and 5 then "Very Good"
when review_rating between 3 and 3.9 then "Good"
when review_rating between 2 and 2.9 then "Average"
else "Bad"
end as review_status
from customer)
select review_status,count(customer_id) as no_of_customers from cte
group by review_status order by no_of_customers desc; 

select * from customer;